export { default as Navbar } from './Navbar.vue'
export { default as Register } from './Register.vue'
export { default as Login } from './Login.vue'
export { default as ForgotPassword } from './ForgotPasswordPage.vue'
export { default as CheckGmailCode } from './CheckGmailCode.vue'
export { default as ResetCode } from './ResetCode.vue'
export {default as CreateProduct} from './CreateProduct.vue'